//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTRS_S1s5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.CPU_Table1 = new HashSet<CPU_Table>();
            this.DataStoreTable1 = new HashSet<DataStoreTable>();
            this.Motherboard_Table1 = new HashSet<Motherboard_Table>();
            this.NIC_Table1 = new HashSet<NIC_Table>();
            this.RAM_Table1 = new HashSet<RAM_Table>();
            this.VideoCardTable1 = new HashSet<VideoCardTable>();
        }
    
        public int id { get; set; }
        public string Inventory_number { get; set; }
        public string Location { get; set; }
        public string IP_adress { get; set; }
        public string MAC_adress { get; set; }
        public Nullable<int> idOS { get; set; }
        public Nullable<int> idOrganization { get; set; }
        public Nullable<int> idDomen { get; set; }
        public string PC_Name { get; set; }
        public Nullable<int> Device_Type { get; set; }
        public Nullable<int> Stock { get; set; }
        public string OPerson { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> RAM { get; set; }
        public string RUM_Num { get; set; }
        public Nullable<int> NIC { get; set; }
        public Nullable<int> Motherboard { get; set; }
        public Nullable<int> DataStore { get; set; }
        public string DataStore_Num { get; set; }
        public Nullable<int> VideoCard { get; set; }
        public string Commentary { get; set; }
    
        public virtual CPU_Table CPU_Table { get; set; }
        public virtual DataStoreTable DataStoreTable { get; set; }
        public virtual Domen Domen { get; set; }
        public virtual Motherboard_Table Motherboard_Table { get; set; }
        public virtual NIC_Table NIC_Table { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual PC_OS PC_OS { get; set; }
        public virtual PC_Type PC_Type { get; set; }
        public virtual RAM_Table RAM_Table { get; set; }
        public virtual Stock Stock1 { get; set; }
        public virtual VideoCardTable VideoCardTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPU_Table> CPU_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataStoreTable> DataStoreTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motherboard_Table> Motherboard_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIC_Table> NIC_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAM_Table> RAM_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCardTable> VideoCardTable1 { get; set; }
    }
}
