//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTRS_S1s5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTRS_BaseEntities : DbContext
    {
        public static RTRS_BaseEntities _context;

        public RTRS_BaseEntities()
                    : base("name=RTRS_BaseEntities")
        {
        }
        public static RTRS_BaseEntities GetContext()
        {
            if (_context == null)
            {
                _context = new RTRS_BaseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<CPU_Table> CPU_Table { get; set; }
        public virtual DbSet<DataStoreTable> DataStoreTable { get; set; }
        public virtual DbSet<Domen> Domen { get; set; }
        public virtual DbSet<Motherboard_Table> Motherboard_Table { get; set; }
        public virtual DbSet<NIC_Table> NIC_Table { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<PC_OS> PC_OS { get; set; }
        public virtual DbSet<PC_Type> PC_Type { get; set; }
        public virtual DbSet<RAM_Table> RAM_Table { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockType> StockType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VC_Label> VC_Label { get; set; }
        public virtual DbSet<VideoCardTable> VideoCardTable { get; set; }
    }
}
